### PR TITLE
Add initial debian packaging info

### PR DESCRIPTION
**Pull request by nekromant**
Signed-off-by: Andrew Andrianov <andrew@ncrmnt.org>

### CODE REVIEW

**Comment by nekromant** [comment]
I've added the basic debian packaging info your stcgal, so that one can build a debian package simply by running debuild or dpkg-buildpackage. You may want to revise version info (I used 0.1git) and the rest. 
I'll be rigging it to my Jenkins CI instance shortly to build packages.

**Comment by grigorig** [comment]
I don't have a lot experience with Debian packaging, but it looks simply and clean. However I think the copyright notice needs some work.

**Comment by nekromant** [comment]
I used dh_make to generate initial stub + some manual editing (python3-pyserial package as a sample) to make it work. It looks like the proper way. Feel free to adjust the copyright part, I haven't touched it.

**Comment by grigorig** [comment]
OK, thanks. I was able to greatly simplify this with pybuild. See the "packaging" branch. I took the liberty to license the packaging stuff as MIT just like the rest of stcgal. Are you OK with that?

(Not that it matters, it's not really any code.)

**Comment by nekromant** [comment]
Absolutely. I've also rigged stcgal to jenkins to build packages automatically and publish to my personal deb repository. Now testing the setup. If you want email notification if a build fails - drop me a line.

**Comment by grigorig** [comment]
Merged with changes, as discussed.

**Pull request closed without merging**
